name: build
on: [push]

jobs:
  ubuntu_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            build-essential \
            cmake \
            libusb-1.0.0-dev \
            python3 \
            python3-pip
      - name: Create Venv
        run: python3 -m venv .venv
      - name: Build
        run: source .venv/bin/activate && python ./setup.py build
      - name: Install
        run: source .venv/bin/activate && python ./setup.py install

